### PR TITLE
This is real. @MazenMC and @stuntguy3000 didn't make it.

### PR DESCRIPTION
**Pull request by DevRoMc**

### CODE REVIEW

**Comment by ibJarrett** [comment]
:+1:

**Comment by stuntguy3000** [comment]
Well... you are not wrong...except...

I have self assigned the title of "Lead of Public Communications and Quality Assurance Officer" for this project. 

@DevRoMc I recommend rewriting it to say something along the lines of 
Original Codebase: Vilsol
Modifications: MazenMC. stuntguy3000 and various GitHub contributors (insert link)

**Comment by ibJarrett** [comment]
@stuntguy3000 :-1:

**Comment by DevRoMc** [comment]
@stuntguy3000 No, the Creator was Vilsol. The Contributors are You, Mazen and all the others who pushed. I would believe there is more people who thinks this PR is right and your current is wrong. 

And... why would you assign yourself a title? What if i want to assign @ibJarrett the title of Lead Officer Dickbutt for the project?

**Comment by stuntguy3000** [comment]
Your point is true, however, I do not think it is appropriate to list the GitHub contributors as the list will be evergrowing, and require constant changes to the code.

**Comment by ibJarrett** [comment]
@stuntguy3000 :-1:

**Comment by stuntguy3000** [comment]
Manually implementing changes.

**Comment by DevRoMc** [comment]
Do it you fagit.

**Comment by DevRoMc** [comment]
@stuntguy3000 So???

**Comment by stuntguy3000** [comment]
So?

**Pull request closed without merging**
